l_english:
 SETTING_DEBUG_SAVES:0 "Hoeveelheid aan Debug Saves"
 SETTING_TUTORIAL:0 "Zelfstudie"
 SETTING_DISABLED_HINTS:0 "Hints uitzetten"
 #SETTING_FOCUS_ON_COMBAT:1 "" # <DELETE THIS KEY>
 SETTING_TOOLTIP_DELAY:1 "Aanwijzingsvertraging"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nSets the delay before tooltips appear."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Ontgrendel vertraging"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nSets the delay before tooltips are unlocked."
 SETTING_TOOLTIP_LOCK_TIME:0 "Vergrendel vertraging"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nSets the delay before tooltips are locked."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Vergrendeld open vertraging"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nSets the delay before tooltips are locked when another tooltip is already open."
 # Audio
 SETTING_Sound_Effects:1 "Alle Geluidseffecten"
 SETTING_Sound_Effects_TOOLTIP:1 "#T Geluidseffecten Volume\n#!Sets the volume of ALL sound effects."
 SETTING_Ambience:0 "Ambiance"
 SETTING_Ambience_TOOLTIP:1 "#T Ambiance Volume\n#!Sets the volume of environmental ambience."
 SETTING_TOOLTIP_MODE:1 "Aanwijzingen modus"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nSets the way tooltips "lock in," enabling tooltips-in-tooltips."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Muis vergrendeling"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nTooltips automatically lock in place until the cursor moves away."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Actie vergrendeling"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nPress #V Middle Mouse#! to lock and unlock tooltips."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Timer vergendeling"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nTooltips are locked in place if the cursor does not move for a short while. #weak (Default setting.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Overig"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Aanwijzingen"
 SETTINGS_CATEGORY_SFX:0 "Specifieke Geluidseffecten"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Algemeen"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Kaartbesturing"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Opgeslagen Spellen"
 SETTINGS_CATEGORY_LANGUAGE:0 "Talen"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Geavanceerd – Algemeen"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP:0 "Geavanceerd – Kaart"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters:0 "Geavanceerd – Karakters"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portretten"
 SETTINGS_CATEGORY_GAME_FLAVOR:0 "Flavour"
 SETTINGS_CATEGORY_MULTIPLAYER:0 "Samenspelen"
 SETTINGS_CATEGORY_MAP:0 "Kaart"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Toon expliciete ziektes en verwondingen"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nSets whether graphic injuries and diseases will be visible on character portraits."
 SETTING_SHOW_NUDITY:0 "Toon naaktheid"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nSets whether characters can be shown nude."
 SETTINGS_CATEGORY_GAME_DLC_MODS:0 "Uitbreidingen"
 SETTING_SHOW_CONTENT_SOURCE:0 "Toon Uitbreiding Gebeurtenissen"
 SETTING_SHOW_CONTENT_SOURCE_TOOLTIP:0 "#T $SETTING_SHOW_CONTENT_SOURCE$#!\nBepaalt of je ziet van welke uitbreiding de Gebeurtenis komt."

 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE:0 "Koninklijk Hof Camera Stilstaand Animatie"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nDetermines if the camera in the Royal Court should pan gently across your Court when idle.\n\nIf Animated Characters is turned off, this setting has no effect."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION:0 "Koniklijk Hof Camera Vloeiende Overgang"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nDetermines if the camera in the Royal Court should move smoothly to a new location.\n\nIf Animated Characters is turned off, this setting has no effect."
 NEVER:0 "Nooit"
 MONTHLY:0 "Elke maand"
 HALFYEAR:0 "Elke 6 maanden"
 YEARLY:0 "Elk jaar"
 FIVE_YEAR:0 "Elke 5 jaar"
 SETTINGS_CATEGORY_TUTORIAL:0 "Zelfstudie"
 SETTING_REACTIVE_TUTORIAL:1 "Toon Reactief Advies"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nSets if the game should show tutorial Advice reacting to how you play. Useful for players new to Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Toon Suggesties"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nSets if the game should suggest something to do at regular intervals. Useful for players new to Crusader Kings III."
 RESET_REACTIVE_ADVICE:0 "Stel Reactief Advies opnieuw in"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T Stel Reactief Advies opniuw in#!\nPreviously seen Reactive Advice will show up once more."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Stel Reactief Advies opniew in"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Weet je zeker dat je Reactief Advies opnieuw in wilt stellen?"
 SETTING_ADVANCED_SHADERS:0 "Geavanceerd Schaduw Effect"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Geavanceerd Schaduw Effect\n#!This option will enable advanced shader effects.\n\nTurning it off may increase performance at the cost of making some effects (e.g. terrain and water) look worse"
 SETTING_WINTER_PARTICLE_EFFECTS:0 "Winter Deeltjes Effection"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP:0 "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nDetermines whether particle effects are shown or not when Winter is active in some areas of the map.\n\nTurning it off may increase performance"
 SETTING_RESET_CAMERA_ROTATION:0 "Camera Draai Opnieuw instellen"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermines if the camera should automatically reset default position after being rotated by the user."
 SETTING_TILT_CAMERA_ON_ZOOM_OUT: "Kantel camera op uitzoom"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP: "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\nDetermines if the camera should tilt towards the default tilt when zooming out."
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS:0 "Hofscene Achtergrond Karakters"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nDetermines if the Royal Court 3D scene should display less important background characters."
 SETTING_MAP_HIGHLIGHT:0 "Kaart Muisaanwijzer Markering"
 SETTING_MAP_HIGHLIGHT_TOOLTIP:0 "#T $SETTING_MAP_HIGHLIGHT$#!\nDetermines the intensity of the cursor highlights on the map"
 BASED_ON_ZOOM_LEVEL:0 "Dynamisch"
 ALWAYS_HIDE:0 "Altijd Verbergen"
 ALWAYS_SHOW:0 "Altijd Tonen"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Kuststreken"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nThis option will control when coastal realm borders should be shown.\nIf $BASED_ON_ZOOM_LEVEL$ then they will be hidden in the detail zoom level.\n\nPicking a $ALWAYS_SHOW$ or $ALWAYS_HIDE$ may increase performance at the cost of the coastal realm borders not hiding dynamically."
 SETTINGS_DISCARD_CHANGES:0 "Veranderingen Verwerpen"
 SETTING_HUD_SKIN:0 "HUD skin"
 hud_skin_auto:0 "Dynamisch"
 default:0 "Standaard"
 iberian:0 "Iberisch"
 Norse:0 "Noors"
 iranian: "$e_persia_adj$"
 SETTING_HUD_SKIN_TOOLTIP:0 "#T $SETTING_HUD_SKIN$#!\nSets visual theme of the HUD interface - 2D UI shown on the main game screen.\n\nIf $hud_skin_auto$ is selected, HUD will change depending on culture, faith and realm capital of the player."
 SETTING_RICH_PRESENCE:0 "Rijkelijke Aanwezigheid"
 SETTING_RICH_PRESENCE_TOOLTIP:0 "#T $SETTING_RICH_PRESENCE$#!\nShow information about your current play session to your friends if your platform supports it."
 SETTING_USE_DYNASTY_NAMED_REALMS:0 "Dynastie Vernoemde Rijken"
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP:0 "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\nSome cultures will name their primary title after their Dynasty (eg: Abbasids)."
 map_table_style_auto: "Dynamisch"
 map_table_style_western: "Standaard"
 map_table_style_ce1: "Plaag"
 SETTING_MAP_TABLE_STYLE: "Kaart Tafel Stijl"
 SETTING_MAP_TABLE_STYLE_TOOLTIP: "#T $SETTING_MAP_TABLE_STYLE$#!\nSets visual style of the map table - the map and 3D environment shown when zoomed out.\n\nIf $map_table_style_auto$ is selected, a map table style will be selected based on the current Player and their character."
 SETTINGS_CATEGORY_STYLING: "Interface Stijl"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS: "Ziekte Graphics"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\nSets if disease effects should be shown on the map"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS: "Legende Graphics"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\nSets if legend effects should be shown on the map"
 SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED: "Papieren Kaart Belichting"
 SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED_TOOLTIP: "#T $SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED$#!\nSets if the paper map should receive lighting and shadows from the map table. (disable this to get the classic paper map coloring)"
 