l_english:
 SETTING_DEBUG_SAVES:0 "Hoeveelheid aan Debug Saves"
 SETTING_TUTORIAL:0 "Zelfstudie"
 SETTING_DISABLED_HINTS:0 "Hints uitzetten"
 #SETTING_FOCUS_ON_COMBAT:1 "" # <DELETE THIS KEY>
 SETTING_TOOLTIP_DELAY:1 "Aanwijzingsvertraging"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nStelt de vertraging in voordat tooltips verschijnen."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Ontgrendel vertraging"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nStelt de vertraging in voordat tooltips worden ontgrendeld."
 SETTING_TOOLTIP_LOCK_TIME:0 "Vergrendel vertraging"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nStelt de vertraging in voordat tooltips worden vergrendeld."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Vergrendeld open vertraging"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nStelt de vertraging in voordat tooltips worden vergrendeld als er al een andere tooltip is geopend."
 # Audio
 SETTING_Sound_Effects:1 "Alle Geluidseffecten"
 SETTING_Sound_Effects_TOOLTIP:1 "#T Geluidseffecten Volume\n#!Stelt het volume van ALLE geluidseffecten in."
 SETTING_Ambience:0 "Ambiance"
 SETTING_Ambience_TOOLTIP:1 "#T Ambiance Volume\n#!Stelt het volume van de omgevingsgeluiden in."
 SETTING_TOOLTIP_MODE:1 "Aanwijzingen modus"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nStelt de manier in waarop tooltips worden "vergrendeld", waardoor tooltips-in-tooltips mogelijk worden."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Muis vergrendeling"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nTooltips worden automatisch vergrendeld totdat de cursor weg beweegt."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Actie vergrendeling"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nPress #V Middelste muisknop#! om tooltips te vergrendelen en te ontgrendelen."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Timer vergendeling"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nTooltips worden vergrendeld als de cursor even niet beweegt. #weak (standaardinstelling)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Overig"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Aanwijzingen"
 SETTINGS_CATEGORY_SFX:0 "Specifieke Geluidseffecten"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Algemeen"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Kaartbesturing"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Opgeslagen Spellen"
 SETTINGS_CATEGORY_LANGUAGE:0 "Talen"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Geavanceerd – Algemeen"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_MAP:0 "Geavanceerd – Kaart"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS_Characters:0 "Geavanceerd – Karakters"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portretten"
 SETTINGS_CATEGORY_GAME_FLAVOR:0 "Persoonlijke voorkeur"
 SETTINGS_CATEGORY_MULTIPLAYER:0 "Samenspelen"
 SETTINGS_CATEGORY_MAP:0 "Kaart"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Toon expliciete ziektes en verwondingen"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nStelt in of grafische verwondingen en ziektes zichtbaar zullen zijn op karakterportretten."
 SETTING_SHOW_NUDITY:0 "Toon naaktheid"
 SETTING_SHOW_NUDITY_TOOLTIP:0 "#T $SETTING_SHOW_NUDITY$#!\nStelt in of personages naakt kunnen worden weergegeven."
 SETTINGS_CATEGORY_GAME_DLC_MODS:0 "Uitbreidingen"
 SETTING_SHOW_CONTENT_SOURCE:0 "Toon Uitbreiding Gebeurtenissen"
 SETTING_SHOW_CONTENT_SOURCE_TOOLTIP:0 "#T $SETTING_SHOW_CONTENT_SOURCE$#!\nBepaalt of je ziet van welke uitbreiding de Gebeurtenis komt."

 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE:0 "Koninklijk Hof Camera Stilstaand Animatie"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_IDLE$#!\nBepaalt of de camera in het Koninklijk Hof zachtjes over het Hof moet pannen als het niet actief is.\n\nAls Geanimeerde personages is uitgeschakeld, heeft deze instelling geen effect."
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION:0 "Koniklijk Hof Camera Vloeiende Overgang"
 SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION_TOOLTIP:0 "#T $SETTING_ROYAL_COURT_ANIMATE_CAMERA_TRANSITION$#!\nBepaalt of de camera in de Koninklijke Hof soepel naar een nieuwe locatie moet bewegen. Als Geanimeerde personages is uitgeschakeld, heeft deze instelling geen effect."
 NEVER:0 "Nooit"
 MONTHLY:0 "Elke maand"
 HALFYEAR:0 "Elke 6 maanden"
 YEARLY:0 "Elk jaar"
 FIVE_YEAR:0 "Elke 5 jaar"
 SETTINGS_CATEGORY_TUTORIAL:0 "Zelfstudie"
 SETTING_REACTIVE_TUTORIAL:1 "Toon Reactief Advies"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nStelt in of het spel tutorialadviezen moet tonen die reageren op hoe je speelt. Handig voor spelers die nieuw zijn in Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Toon Suggesties"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nSets if the game should suggest something to do at regular intervals. Useful for players new to Crusader Kings III."
 RESET_REACTIVE_ADVICE:0 "Stel Reactief Advies opnieuw in"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T Stel Reactief Advies opniuw in#!\nEerder getoonde Reactieve Adviezen zullen opnieuw verschijnen."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Stel Reactief Advies opniew in"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Weet je zeker dat je Reactief Advies opnieuw in wilt stellen?"
 SETTING_ADVANCED_SHADERS:0 "Geavanceerd Schaduw Effect"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Geavanceerd Schaduw Effect\n#!Deze optie schakelt geavanceerde schaduweffecten in.\n\nHet uitschakelen kan de prestaties verhogen ten koste van bepaalde effecten (zoals terrein en water)."
 SETTING_WINTER_PARTICLE_EFFECTS:0 "Winter Deeltjes Effecten"
 SETTING_WINTER_PARTICLE_EFFECTS_TOOLTIP:0 "#T $SETTING_WINTER_PARTICLE_EFFECTS$#!\nBepaalt of de zwevende deeltjes effecten wel of niet getoond worden als de Winter actief is in sommige delen van de kaart.\n\nHet uitschakelen kan de prestaties verhogen"
 SETTING_RESET_CAMERA_ROTATION:0 "Camera Draai Opnieuw instellen"
 SETTING_RESET_CAMERA_ROTATION_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nBepaalt of de camera automatisch de standaardpositie moet herstellen nadat deze door de gebruiker is gedraaid."
 SETTING_TILT_CAMERA_ON_ZOOM_OUT: "Kantel camera op uitzoom"
 SETTING_TILT_CAMERA_ON_ZOOM_OUT_TOOLTIP: "#T $SETTING_TILT_CAMERA_ON_ZOOM_OUT$#!\nBepaalt of de camera moet kantelen in de richting van de standaard kanteling bij het uitzoomen."
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS:0 "Hofscene Achtergrond Karakters"
 SETTING_COURT_SCENE_LOW_PRIORITY_CHARACTERS_TOOLTIP:0 "#T $SETTING_RESET_CAMERA_ROTATION$#!\nBepaalt of de Koninklijke Hof 3D-scène minder belangrijke achtergrondfiguren moet weergeven."
 SETTING_MAP_HIGHLIGHT:0 "Kaart Muisaanwijzer Markering"
 SETTING_MAP_HIGHLIGHT_TOOLTIP:0 "#T $SETTING_MAP_HIGHLIGHT$#!\nBepaalt de intensiteit van de cursor-highlights op de kaart"
 BASED_ON_ZOOM_LEVEL:0 "Dynamisch"
 ALWAYS_HIDE:0 "Altijd Verbergen"
 ALWAYS_SHOW:0 "Altijd Tonen"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Kuststreken"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nDeze optie bepaalt wanneer de randen van het kustgebied getoond moeten worden.\nAls $BASED_ON_ZOOM_LEVEL$ worden ze verborgen in het detailzoomniveau.\n\nAls $ALWAYS_SHOW$ of $ALWAYS_HIDE$ gekozen wordt, kan dit de prestaties verhogen, maar dan worden de kustgebieden niet meer dynamisch verborgen."
 SETTINGS_DISCARD_CHANGES:0 "Veranderingen Verwerpen"
 SETTING_HUD_SKIN:0 "HUD uiterlijk"
 hud_skin_auto:0 "Dynamisch"
 default:0 "Standaard"
 iberian:0 "Iberisch"
 Norse:0 "Noors"
 iranian: "$e_persia_adj$"
 SETTING_HUD_SKIN_TOOLTIP:0 "#T $SETTING_HUD_SKIN$#!\nStelt het visuele thema van de HUD-interface in - 2D UI op het hoofdscherm van het spel.\n\nAls $hud_skin_auto$ is selected, is geselecteerd, zal de HUD veranderen afhankelijk van de cultuur, het geloof en de rijkshoofdstad van de speler."
 SETTING_RICH_PRESENCE:0 "Rijkelijke Aanwezigheid"
 SETTING_RICH_PRESENCE_TOOLTIP:0 "#T $SETTING_RICH_PRESENCE$#!\nToon informatie over je huidige speelsessie aan je vrienden als je platform dit ondersteunt."
 SETTING_USE_DYNASTY_NAMED_REALMS:0 "Dynastie Vernoemde Rijken"
 SETTING_USE_DYNASTY_NAMED_REALMS_TOOLTIP:0 "#T $SETTING_USE_DYNASTY_NAMED_REALMS$#!\nSommige culturen noemen hun primaire titel naar hun dynastie (bijv. Abbasiden)."
 map_table_style_auto: "Dynamisch"
 map_table_style_western: "Standaard"
 map_table_style_ce1: "Plaag"
 SETTING_MAP_TABLE_STYLE: "Kaarttafel Stijl"
 SETTING_MAP_TABLE_STYLE_TOOLTIP: "#T $SETTING_MAP_TABLE_STYLE$#!\nStelt de visuele stijl van de kaarttafel in - de kaart en 3D-omgeving die worden weergegeven als je uitzoomt.\n\nAls $map_table_style_auto$ is geselecteerd, wordt een stijl voor de kaarttafel geselecteerd op basis van de huidige speler en zijn personage."
 SETTINGS_CATEGORY_STYLING: "Interface Stijl"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS: "Ziekte Graphics"
 SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_EPIDEMIC_MAP_GRAPHICS$#!\nStelt in of ziekte-effecten moeten worden weergegeven op de kaart"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS: "Legenda Graphics"
 SETTING_SHOW_LEGEND_MAP_GRAPHICS_TOOLTIP: "#T $SETTING_SHOW_LEGEND_MAP_GRAPHICS$#!\nStelt in of legenda-effecten moeten worden weergegeven op de kaart"
 SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED: "Papieren Kaart Belichting"
 SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED_TOOLTIP: "#T $SETTING_HAS_FLAT_MAP_LIGHTING_ENABLED$#!\nStelt in of de papieren kaart verlichting en schaduwen moet krijgen van de kaarttafel. (schakel dit uit om de klassieke papieren kaartkleuring te krijgen)"
 
