l_english:
 SETTING_AUTOSAVE:0 "Tijd tussen auto-opslag pogingen"
 SETTING_DEBUG_SAVES:0 "Aantal debug opslagen"
 SETTING_TUTORIAL:0 "Zelfstudie"
 SETTING_DISABLED_HINTS:0 "Hints Uitgeschakeld"
 SETTING_FOCUS_ON_COMBAT:0 "Focus op strijden"
 SETTING_TOOLTIP_DELAY:1 "Aanwijzingsvertraging"
 SETTING_TOOLTIP_DELAY_TOOLTIP:1 "#T $SETTING_TOOLTIP_DELAY$#!\nStelt de vertraging voordat een Aanwijzing ontstaat in."
 SETTING_TOOLTIP_UNLOCK_TIME:0 "Ontgrendel vertraging"
 SETTING_TOOLTIP_UNLOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_UNLOCK_TIME$#!\nStelt de vertraging voordat een Aanwijzing wordt ontgrendeld in."
 SETTING_TOOLTIP_LOCK_TIME:0 "Vergrendel vertraging"
 SETTING_TOOLTIP_LOCK_TIME_TOOLTIP:1 "#T $SETTING_TOOLTIP_LOCK_TIME$#!\nStelt de vertraging voordat een Aanwijzing wordt vergrendeld in."
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED:0 "Vergrendeld open vertraging"
 SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED_TOOLTIP:1 "#T $SETTING_TOOLTIP_OPEN_TIME_WHEN_ANOTHER_LOCKED$#!\nZet de vertraging voordat een Aanwijzing vergrendeld wordt, wanneer een andere al open staat."
 # Audio
 SETTING_Sound_Effects:1 "Geluidseffecten"
 SETTING_Sound_Effects_TOOLTIP:1 "#T Geluidseffect Volume\n#!Zet het volume van de geluidseffecten."
 SETTING_Ambience:0 "Sfeer"
 SETTING_Ambience_TOOLTIP:1 "#T Sfeer Volume\n#!Zet het volume van de sfeermuziek."
 SETTING_TOOLTIP_MODE:1 "Aanwijzingen modus"
 SETTING_TOOLTIP_MODE_TOOLTIP:3 "#T $SETTING_TOOLTIP_MODE$#!\nStelt de manier in hoe een Aanwijzing zich " vergrendelt " op deze manier kan je een Aanwijzing in een Aanwijzing krijgen."
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY:0 "Muis vergrendeling"
 SETTING_TOOLTIP_MODE_MOUSE_TENDENCY_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_MOUSE_TENDENCY$#!\nAanwijzingen blijven in de plaats, totdat de cursor zich verplaatst."
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION:0 "Actie vergrendeling"
 SETTING_TOOLTIP_MODE_LOCK_ON_ACTION_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_ACTION$#!\nDruk op de #V Middelmuisknop#! om Aanwijzing te vergrendelen en ontgrendelen."
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER:0 "Timer vergrendeling"
 SETTING_TOOLTIP_MODE_LOCK_ON_TIMER_TOOLTIP:0 "#T $SETTING_TOOLTIP_MODE_LOCK_ON_TIMER$#!\nAanwijzingen worden op hun plek gehouden als de cursor zich voor een tijdje niet verplaatst. #weak (Standaard instelling.)#!"
 SETTINGS_CATEGORY_INTERFACE_MISC:0 "Overig"
 SETTINGS_CATEGORY_TOOLTIPS:0 "Aanwijzingen"
 SETTINGS_CATEGORY_SFX:0 "Specifieke Geluidseffecten"
 SETTINGS_CATEGORY_AUDIO_GENERAL:0 "Algemeen"
 SETTINGS_CATEGORY_MAP_CONTROLS:0 "Kaart besturing"
 SETTINGS_CATEGORY_SAVE_GAMES:0 "Opgeslagen Spellen"
 SETTINGS_CATEGORY_LANGUAGE:0 "Taal"
 SETTINGS_CATEGORY_ADVANCED_GRAPHICS:0 "Geavanceerd"
 SETTINGS_CATEGORY_GAME_PORTRAITS:0 "Portretten"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS:0 "Laat aanstotelijke ziekten en verwondingen zien"
 SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS_TOOLTIP:0 "#T $SETTING_SHOW_DISTURBING_PORTRAIT_MODIFIERS$#!\nStelt in of er aanstootgrijpende effecten van ziekte of verwondingen moet worden laten zien op de portretten van in-game karakters. #V Let op: Dit kan zeer vies uitpakken.#!"
 NEVER:0 "Nooit"
 MONTHLY:0 "Elke maand"
 HALFYEAR:0 "Elke 6 maanden"
 YEARLY:0 "Elk jaar"
 FIVE_YEAR:0 "Elke 5 jaar"
 SETTINGS_CATEGORY_TUTORIAL:0 "Zelfstudie"
 SETTING_REACTIVE_TUTORIAL:1 "Laat Reactief Advies zien"
 SETTING_REACTIVE_TUTORIAL_TOOLTIP:0 "#T $SETTING_REACTIVE_TUTORIAL$#!\nStelt in of het spel reactief advies moet geven op basis van je gameplay. Dit kan handig zijn voor nieuwe spelers van Crusader Kings III."
 SETTING_SHOW_SUGGESTIONS:0 "Laat suggesties zien"
 SETTING_SHOW_SUGGESTIONS_TOOLTIP:2 "#T $SETTING_SHOW_SUGGESTIONS$#!\nStelt in of de game je suggesties geeft voor wat je kan doen op bepaalde momenten. Dit kan handig zijn voor nieuwe spelers van Crusader Kings III."
 RESET_REACTIVE_ADVICE:0 "Reset Reactief Advies"
 RESET_REACTIVE_ADVICE_TOOLTIP:1 "#T Reset Reactive Advice#!\nReactief Advies wat eens is getoond zal terugkeren."
 RESET_REACTIVE_ADVICE_CONFIRMATION_TITLE:0 "Reset Reactief Advies"
 RESET_REACTIVE_ADVICE_CONFIRMATION_TEXT:0 "Weet je zeker dat je Reactief Advies wilt resetten?"
 SETTING_ADVANCED_SHADERS:0 "Geavanceerde Schaduweffecten"
 SETTING_ADVANCED_SHADERS_TOOLTIP:0 "#T Advanced Shader Effects\n#!Deze optie zal geavanceerde schaduweffecten aanzetten.\n\nDit uitzetten kan spelprestaties verbeteren met als nadeel dat bepaalde spelelementen (zoals: terrein en water) er slechter uit zullen zien."
 BASED_ON_ZOOM_LEVEL:0 "Dynamisch"
 ALWAYS_HIDE:0 "Altijd verbergen"
 ALWAYS_SHOW:0 "Altijd tonen"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM:0 "Kustgrenzen"
 SETTING_HIDE_COAST_BORDER_ON_ZOOM_TOOLTIP:0 "#T $SETTING_HIDE_COAST_BORDER_ON_ZOOM$#!\nDeze optie stelt in wanneer de kustgrenzen van een rijk worden getoond.\nAls je voor $BASED_ON_ZOOM_LEVEL$ kiest dan zullen zij verborgen worden in het meer gedetailleerdere zoomniveau.\n\nAls je kiest voor $ALWAYS_SHOW$ of $ALWAYS_HIDE$ zal het wellicht spelprestaties verbeteren met als nadeel dat deze niet dynamisch worden getoond of verborgen."
 
