l_english:
 # General 
 SETTING_VALUE_NONE:1 "$VALUE$"
 SETTING_VALUE_TOTAL_PERCENTAGE:0 "$VALUE|%/0$"
 SETTING_VALUE_PERCENTAGE:0 "$VALUE|%0$"
 SETTING_VALUE_SECONDS:1 "$VALUE$ seconden"
 # Graphics
 SETTING_RENDERER:0 "Renderer"
 SETTING_VSYNC:0 "VSync"
 SETTING_VSYNC_TOOLTIP:3 "#T $SETTING_VSYNC$\n#!Zorgt ervoor dat het spel dezelfde verversingsnelheid als je monitor aanhoudt, wat Tearing kan verminderen.\n\nHet uitzetten hiervan kan spelprestaties verbeteren."
 SETTING_MULTI_SAMPLING:0 "Anti-aliasing (MSAA)"
 SETTING_MULTI_SAMPLING_TOOLTIP:2 "#T $SETTING_MULTI_SAMPLING$\n#!Het gebruik maken van Multisampling (MSAA) zorgt ervoor dat de hoeken van graphics zachter worden.\n\nLagere instellingen kunnen prestaties verbeteren."
 SETTING_ANTI_ALIASING:0 "Anti-Aliasing"
 SETTING_ANTI_ALIASING_TOOLTIP:0 "#T $SETTING_ANTI_ALIASING$\n#!Het gebruik maken van anti-aliasing zorgt ervoor dat de hoeken van graphics zachter worden.\n\nFXAA is aanbevolen."
 OPTION_ANTI_ALIASING_DISABLED:0 "Uitgeschakeld"
 OPTION_ANTI_ALIASING_FXAA:0 "FXAA"
 SETTING_ANISOTROPIC_FILTERING:0 "Textuur Filtering"
 SETTING_ANISOTROPIC_FILTERING_TOOLTIP:2 "#T $SETTING_ANISOTROPIC_FILTERING$\n#!Het gebruik maken van anisotrope filtering zal getextureerde opervlakken beter eruit laten zien.\n\nLagere instellingen kunnen spelprestaties verbeteren."
 SETTING_FULLSCREEN_RESOLUTION:0 "Resolutie"
 SETTING_FULLSCREEN_RESOLUTION_TOOLTIP:2 "#T $SETTING_FULLSCREEN_RESOLUTION$\n#!Stelt de beeldkwaliteit van het spel in.\n\nLagere resoluties zullen spelprestaties verbeteren."
 SETTING_WINDOWED_RESOLUTION:0 "Venster modus"
 SETTING_WINDOWED_RESOLUTION_TOOLTIP:0 "Resolutie van het spel. Een hogere resolutie kost meer kracht."
 SETTING_DISPLAY:0 "Monitor"
 SETTING_DISPLAY_TOOLTIP:2 "#T $SETTING_DISPLAY$\n#!Als jouw computer meerdere monitoren heeft kun je hier kiezen welke je wilt gebruiken voor het spel."
 SETTING_GRAPHICS_DEVICE:0 "Grafische Kaart"
 SETTING_GRAPHICS_DEVICE_TOOLTIP:2 "#T $SETTING_GRAPHICS_DEVICE$\n#!Kiest welke grafische kaart het spel moet gebruiken. \n\nEen geïntegreerde grafische kaart of software renderer kunnen spelprestaties verminderen."
 SETTING_SHADOW_MAP_RESOLUTION:0 "Schaduw Kwaliteit"
 SETTING_SHADOW_MAP_RESOLUTION_TOOLTIP:2 "#T $SETTING_SHADOW_MAP_RESOLUTION$\n#!Bepaald met welke resoluties schaduwen worden gerenderd.\n\nLagere instellingen kunnen spelprestaties verbeteren."
 SETTING_DISPLAY_MODE:0 "Weergave Modus"
 SETTING_DISPLAY_MODE_TOOLTIP:2 "#T $SETTING_DISPLAY_MODE$\n#!Bepaald hoe het spel op jouw scherm moet worden weergegeven."
 SETTING_BLOOM:0 "Bloom"
 SETTING_MESH_LOD_BIAS:0 "Mesh LOD Kwaliteit"
 SETTING_MESH_LOD_FADE:0 "Mesh LOD Overgang"
 SETTING_TERRAIN_SMOOTHING:1 "Terrein Verzachting"
 OPTION_FULLSCREEN:0 "Volledig Scherm"
 OPTION_FULLSCREEN_TOOLTIP:0 "#T $OPTION_FULLSCREEN$\n#!Geeft het spel over het volledige scherm weer. De resolutie instellingen bepalen hierbij hoe scherp het wordt weergegeven."
 OPTION_BORDERLESS_FULLSCREEN:0 "Vensterloos volledig scherm"
 OPTION_BORDERLESS_FULLSCREEN_TOOLTIP:0 "#D cut#!"
 OPTION_WINDOWED:0 "Venster modus"
 OPTION_WINDOWED_TOOLTIP:0 "#T $OPTION_WINDOWED$\n#!Geeft het spel in een venster weer. De resolutie instellingen bepalen de grootte van het venster."
 OPTION_DISABLED:1 "Uitgeschakeld"
 OPTION_OFF:0 "Uit"
 OPTION_LOW:0 "Laag"
 OPTION_MEDIUM:0 "Medium"
 OPTION_HIGH:0 "Hoog"
 OPTION_ULTRA:1 "Ultra"
 OPTION_CUSTOM:0 "Op maat"
 OPTION_DEFAULT:1 "Standaard"
 SETTINGS_CATEGORY_UI:0 "Interface"
 SETTINGS_CATEGORY_GAME:0 "Spel"
 SETTING_TEXTURE_QUALITY:1 "Textuur Kwaliteit"
 SETTING_TEXTURE_QUALITY_TOOLTIP:1 "#T $SETTING_TEXTURE_QUALITY$#!\nBepaald de resolutie van de Textuur lader.\n\nLagere instellingen kunnen spelprestaties verbeteren."
 SETTING_QUALITY:0 "Vooraf Ingestelde Kwaliteit"
 SETTING_SFX:0 "Geluidseffecten"
 SETTING_UI:0 "Interface"
 SETTING_QUALITY_TOOLTIP:3 "#T $SETTING_QUALITY$\n#!Kies vooringestelde opties voor de geavanceerde grafische instellingen.\n\nLagere opties zullen voor betere spelprestaties zorgen."
 SETTING_BLOOM_TOOLTIP:3 "#T $SETTING_BLOOM$\n#!Activeert een "bloom" effect, waar extreme licht effecten zullen overschijnen naar andere objecten.\n\nUitzetten kan voor betere spelprestaties zorgen."
 SETTING_REFRACTION_TOOLTIP:0 "Determines whether refractions appear on water or not."
 SETTING_REFRACTION_QUALITY_TOOLTIP:3 "#T $SETTING_REFRACTION_QUALITY$#!\nBepaald de kwaliteit van water refracties, als die aanstaan.\n\nLagere instellingen kunnen spelprestaties verbeteren."
 SETTING_MAPOBJECT_QUALITY_TOOLTIP:0 "Bepaald de hoogste kwaliteit van kaartobjecten (zoals gebouwen)."
 SETTING_MESH_LOD_BIAS_TOOLTIP:0 "Bepaald de kwaliteit van LODs (Levels of detail) op kaartobjecten, zoals legermodellen."
 SETTING_MESH_LOD_FADE_TOOLTIP:3 "#T $SETTING_MESH_LOD_FADE$\n#!Als het aanstaat zal deze optie soepeler overgaan tussen verschillende LOD (Levels of detail).\n\nUitzetten kan voor betere spelprestaties zorgen."
 SETTING_PROVINCE_NAMES_TOOLTIP:0 "Bepaald hoe Stad en Provincie namen zich op de kaart vertonen."
 SETTING_FILL_IN_IMPASSABLE_TERRAIN_TOOLTIP:0 "Bepaald of onbereikbaar terrein deel uitmaakt van een Rijk zijn grenzen op de kaart."
 SETTING_LANGUAGE_TOOLTIP:3 "#T $SETTING_LANGUAGE$#!\nBepaald de taal van het spel."
 SETTING_ACCOUNT_EMAIL_TOOLTIP:0 "Jouw Paradox Account E-mail"
 SETTING_FRAMERATE_CAP:0 "Limiteer Verversingssnelheid"
 SETTING_FRAMERATE_CAP_TOOLTIP:0 "Limiteerd de verversingssnelheid van het spel tot een bepaalde waarde"
 OPTION_CAP_30:0 "30"
 OPTION_CAP_60:0 "60"
 OPTION_CAP_90:0 "90"
 OPTION_CAP_120:0 "120"
 OPTION_CAP_144:0 "144"
 OPTION_CAP_165:0 "165"
 # GUI
 SETTING_ANIMATION_SPEED:0 "Animatie Snelheid"
 SETTING_GUI_SCALING:0 "GUI Schaal"
 SETTING_GUI_SCALING_TOOLTIP:3 "#T $SETTING_GUI_SCALING$\n#!Bepaald de schaal van de volledige UI. Handig voor hogere resoluties.\n\n#X Als je het te hoog zet zullen niet alle spelelementen goed op het scherm te zien zijn!#!"
 # System
 SETTING_MOUSE_PANNING:0 "Scherm Rand Scrollen"
 SETTING_MOUSE_PANNING_TOOLTIP:3 "#T $SETTING_MOUSE_PANNING$\n#!Bepaald of de kaart mee moet bewegen, als de cursor zich op de rand van het scherm of venster bevindt."
 SETTING_SCROLL_SPEED:0 "Scroll snelheid"
 SETTING_CAMERA_ROTATION_SPEED:0 "Camera draaisnelheid"
 SETTING_ZOOM_SPEED:0 "Zoom snelheid"
 SETTING_INPUT_DEVICE:0 "Invoerapparaat"
 SETTING_EDITOR:0 "Editor"
 SETTING_EDITOR_POSTFIX:0 "Editor postfix"
 SETTING_EDITOR_OPEN_FILE_FORMAT:0 "Editor open command"
 SETTING_LOG_VIEWER_OPEN_FILE_FORMAT:0 "View log command"
 SETTING_GRACEFUL_EXIT:0 "Sierlijk verlaten"
 SETTING_LANGUAGE:0 "Taal"
 MOUSE_AND_KEYBOARD:0 "Muis en keyboard"
 GAMEPAD:0 "Controller"
 SETTING_MULTISAMPLING_DISABLED:0 "Uitgeschakeld"
 SETTING_ANISOTROPIC_FILTERING_DISABLED:0 "Uitgeschakeld"
 # Editor
 SETTING_CAMERA_TILT:0 "Camera tilt"
 SETTING_CAMERA_STRATEGY:0 "Camera type"
 SETTING_CENTERED_ZOOM_IN:0 "Centered zoom-in"
 SETTING_CAMERA_SPEED:0 "Camera snelheid"
 CAMERA_TABLETOP:0 "Table top"
 CAMERA_FPS:0 "Eerste persoon"
 CAMERA_WASD:0 "WASD-stijl"
 # Audio
 SETTING_Music:0 "Muziek"
 SETTING_Ambient:0 "Sfeer"
 SETTING_Effects:0 "Effecten"
 SETTING_Master:0 "Meester"
 SETTING_Master_TOOLTIP:0 "#T Master Volume\n#!Zet het volume van al het geluid in het spel."
 SETTING_Music_TOOLTIP:0 "#T Music Volume\n#!Zet het volume van de muziek."
 SETTING_Ambient_TOOLTIP:0 "#T Ambient Volume\n#!Zet het volume van de omgevings sfeer."
 SETTING_SFX_TOOLTIP:0 "#T SFX Volume\n#!Zet het volume van geluidseffecten zoals veldslagen."
 SETTING_UI_TOOLTIP:0 "#T Interface Volume\n#!Zet het volume van de UI."
 # Game
 SETTING_AUTOSAVE_TOOLTIP:3 "#T $SETTING_AUTOSAVE$\n#!Bepaald hoe vaak het spel automatisch opslaat."
 SETTING_AUTOSAVE_TO_CLOUD_TOOLTIP:0 "Bepaald of automatisch opgeslagen spellen automatisch naar de Cloud gaan."
 SETTING_CAMERA_FACE_NORTH_TOOLTIP:0 "Bepaald of de camera altijd naar het noorden zal wijzen of niet."
 NO_AUTOSAVE:0 "Niet automatisch opslaan"
