l_english:
 SETTINGS_PAGE_GRAPHICS:0 "Video"
 SETTINGS_PAGE_GAME:0 "Spel"
 SETTINGS_PAGE_SYSTEM:0 "Systeem"
 SETTINGS_PAGE_CONTROLS:0 "Besturing"
 SETTINGS_PAGE_EDITOR:0 "Editor"
 SETTINGS_PAGE_INTERFACE:0 "Interface"
 SETTINGS_PAGE_AUDIO:0 "Audio"
 SETTINGS_CATEGORY_SCREEN:0 "Scherm"
 SETTINGS_CATEGORY_QUALITY:0 "Kwaliteit"
 OPTION_EASY:0 "Makkelijk"
 OPTION_NORMAL:0 "Normaal"
 OPTION_HARD:0 "Moeilijk"
 OPTION_NEVER:0 "Nooit"
 OPTION_MONTHLY:0 "Elke maand"
 OPTION_HALFYEAR:0 "Elk half jaar"
 OPTION_YEARLY:0 "Elk jaar"
 OPTION_FIVE_YEAR:0 "Elke vijf jaar"
 OPTION_NO_AUTOSAVE:0 "Sla niet automatisch op"
 SETTINGS_CATEGORY_ACCOUNT:0 "Account"
 SETTINGS_CATEGORY_SYSTEM:0 "Systeem"
 SETTINGS_CATEGORY_CONTROLS:0 "Besturing"
 SETTINGS_CATEGORY_CAMERA:0 "Camera"
 SETTINGS_CATEGORY_AUDIO:0 "Audio"
 SETTINGS_CATEGORY_GUI:0 "GUI"
 RESTORE:0 "Herstel"
 SAVE_AND_CLOSE:0 "OK"
 SETTINGS:0 "Instellingen"
 REQUIRES_RESTART:0 "Vereist een herstart"
 REQUIRE_RESTART_DESCRIPTION:0 "Sommige instellingen zullen niet toegepast worden, totdat je de game herstart."
